# Generated by Django 6.0.3 on 2026-04-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish_at',
            field=models.DateTimeField(blank=True, help_text='Set together with status=scheduled for auto-publishing by Celery Beat.', null=True, verbose_name='Publish at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('PB', 'Published'), ('SC', 'Scheduled')], default='DR', max_length=2),
        ),
    ]
