services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 settings.asgi:application
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=blog_api.settings.env.prod
    env_file:
      - settings/.env
    volumes:
      - sqlite_data:/app/data
      - static_volume:/usr/src/app/static
    depends_on:
      redis:
        condition: service_healthy
    expose:
      - "8000"

  celery_worker:
    build: .
    command: celery -A settings worker -l info
    env_file:
      - settings/.env
    depends_on:
      redis:
        condition: service_healthy

  celery_beat:
    build: .
    command: celery -A settings beat -l info
    env_file:
      - settings/.env
    depends_on:
      redis:
        condition: service_healthy

  flower:
      build: .
      command: sh -c "celery -A settings flower --basic-auth=$$BLOG_FLOWER_USER:$$BLOG_FLOWER_PASSWORD"
      ports:
        - "5555:5555"
      env_file:
        - settings/.env
      depends_on:
        redis:
          condition: service_healthy
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/static
    depends_on:
      - web

volumes:
  sqlite_data:
  static_volume:
